-- MySQL Script generated by MySQL Workbench
-- Wed Aug 13 16:03:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab4` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `lab4` ;

-- -----------------------------------------------------
-- Table `lab4`.`hocvien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`hocvien` ;

CREATE TABLE IF NOT EXISTS `lab4`.`hocvien` (
  `MaHocVien` VARCHAR(10) NOT NULL,
  `HoTen` VARCHAR(100) NOT NULL,
  `NgaySinh` DATE NULL DEFAULT NULL,
  `GioiTinh` SMALLINT NULL DEFAULT NULL COMMENT '1: Nam, 2: Nữ, 3: Khác',
  `QueQuan` VARCHAR(100) NULL DEFAULT NULL,
  `DiaChi` VARCHAR(200) NULL DEFAULT NULL,
  `TrinhDo` VARCHAR(50) NULL DEFAULT NULL,
  `DienThoai` VARCHAR(15) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `NgayDangKy` DATETIME NOT NULL,
  `TrangThai` SMALLINT NULL DEFAULT '1' COMMENT '1: Đang học, 2: Tạm nghỉ, 3: Nghỉ học',
  PRIMARY KEY (`MaHocVien`),
  UNIQUE INDEX `uk_hocvien_email` (`Email` ASC) VISIBLE,
  INDEX `idx_hocvien_hoten` (`HoTen` ASC) VISIBLE,
  INDEX `idx_hocvien_dienthoai` (`DienThoai` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`monhoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`monhoc` ;

CREATE TABLE IF NOT EXISTS `lab4`.`monhoc` (
  `MaMonHoc` VARCHAR(10) NOT NULL,
  `TenMonHoc` VARCHAR(100) NOT NULL,
  `CapDo` SMALLINT NULL DEFAULT '1' COMMENT '1: Cơ bản, 2: Trung bình, 3: Nâng cao',
  `SoTiet` INT NOT NULL,
  `HocPhi` DECIMAL(10,2) NULL DEFAULT NULL,
  `MoTa` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`MaMonHoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`hoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`hoc` ;

CREATE TABLE IF NOT EXISTS `lab4`.`hoc` (
  `MaHocVien` VARCHAR(10) NOT NULL,
  `MaMonHoc` VARCHAR(10) NOT NULL,
  `NgayBatDauHoc` DATE NULL DEFAULT NULL,
  `NgayKetThucHoc` DATE NULL DEFAULT NULL,
  `TrangThai` SMALLINT NULL DEFAULT '1' COMMENT '1: Đang học, 2: Hoàn thành, 3: Bỏ học',
  PRIMARY KEY (`MaHocVien`, `MaMonHoc`),
  INDEX `MaMonHoc` (`MaMonHoc` ASC) VISIBLE,
  CONSTRAINT `hoc_ibfk_1`
    FOREIGN KEY (`MaHocVien`)
    REFERENCES `lab4`.`hocvien` (`MaHocVien`)
    ON DELETE CASCADE,
  CONSTRAINT `hoc_ibfk_2`
    FOREIGN KEY (`MaMonHoc`)
    REFERENCES `lab4`.`monhoc` (`MaMonHoc`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`chungchi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`chungchi` ;

CREATE TABLE IF NOT EXISTS `lab4`.`chungchi` (
  `MaChungChi` VARCHAR(10) NOT NULL,
  `MaHocVien` VARCHAR(10) NOT NULL,
  `MaMonHoc` VARCHAR(10) NOT NULL,
  `NgayCap` DATE NOT NULL,
  `DiemTongKet` DECIMAL(3,1) NULL DEFAULT NULL,
  `XepLoai` SMALLINT GENERATED ALWAYS AS ((case when (`DiemTongKet` >= 9) then 1 when (`DiemTongKet` >= 8) then 2 when (`DiemTongKet` >= 6.5) then 3 when (`DiemTongKet` >= 5) then 4 else NULL end)) STORED COMMENT '1: Xuất sắc, 2: Giỏi, 3: Khá, 4: Trung bình',
  `TrangThai` SMALLINT NULL DEFAULT '1' COMMENT '1: Có hiệu lực, 2: Hết hiệu lực',
  `SoSeri` VARCHAR(20) NULL DEFAULT NULL,
  `GhiChu` TEXT NULL DEFAULT NULL,
  `NgayTao` DATETIME NULL,
  PRIMARY KEY (`MaChungChi`),
  UNIQUE INDEX `uk_chungchi_hocvien_monhoc` (`MaHocVien` ASC, `MaMonHoc` ASC) VISIBLE,
  UNIQUE INDEX `SoSeri` (`SoSeri` ASC) VISIBLE,
  INDEX `idx_chungchi_ngaycap` (`NgayCap` ASC) VISIBLE,
  INDEX `idx_chungchi_soseri` (`SoSeri` ASC) VISIBLE,
  CONSTRAINT `chungchi_ibfk_1`
    FOREIGN KEY (`MaHocVien` , `MaMonHoc`)
    REFERENCES `lab4`.`hoc` (`MaHocVien` , `MaMonHoc`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`khoahoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`khoahoc` ;

CREATE TABLE IF NOT EXISTS `lab4`.`khoahoc` (
  `MaKhoaHoc` VARCHAR(10) NOT NULL,
  `NgayKhaiGiang` DATE NOT NULL,
  `TenKhoaHoc` VARCHAR(100) NULL DEFAULT NULL,
  `TrangThai` SMALLINT NOT NULL DEFAULT 1 COMMENT '1: Sắp khai giảng, 2: Đang học, 3: Kết thúc',
  `NgayTao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MaKhoaHoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`giaovien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`giaovien` ;

CREATE TABLE IF NOT EXISTS `lab4`.`giaovien` (
  `MaGiaoVien` VARCHAR(10) NOT NULL,
  `HoTen` VARCHAR(100) NOT NULL,
  `NgaySinh` DATE NULL DEFAULT NULL,
  `GioiTinh` SMALLINT NULL DEFAULT NULL COMMENT '1: Nam, 2: Nữ, 3: Khác',
  `DiaChi` VARCHAR(200) NULL DEFAULT NULL,
  `NoiCongTac` VARCHAR(100) NULL DEFAULT NULL,
  `DienThoai` VARCHAR(15) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `ChuyenMon` VARCHAR(200) NULL DEFAULT NULL,
  `KinhNghiem` SMALLINT NOT NULL DEFAULT 0 COMMENT '1: Cao Đẳng\n2: Đại Học\n3: Thạc Sĩ\n4: TIến Sĩ',
  PRIMARY KEY (`MaGiaoVien`),
  UNIQUE INDEX `uk_giaovien_email` (`Email` ASC) VISIBLE,
  INDEX `idx_giaovien_hoten` (`HoTen` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`lophoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`lophoc` ;

CREATE TABLE IF NOT EXISTS `lab4`.`lophoc` (
  `MaLop` VARCHAR(10) NOT NULL,
  `TenLop` VARCHAR(100) NOT NULL,
  `SoHocVienDuKien` INT NOT NULL,
  `SoHocVienThucTe` INT NULL DEFAULT '0',
  `NgayBatDau` DATE NULL DEFAULT NULL,
  `NgayKetThuc` DATE NULL DEFAULT NULL,
  `ThoiGianHoc` VARCHAR(50) NULL DEFAULT NULL,
  `PhongHoc` VARCHAR(20) NULL DEFAULT NULL,
  `TrangThai` SMALLINT NULL DEFAULT '1' COMMENT '1: Chưa khai giảng, 2: Đang học, 3: Kết thúc',
  `MaKhoaHoc` VARCHAR(10) NOT NULL,
  `MaMonHoc` VARCHAR(10) NOT NULL,
  `MaGiaoVien` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`MaLop`),
  INDEX `idx_lophoc_khoahoc` (`MaKhoaHoc` ASC) VISIBLE,
  INDEX `idx_lophoc_monhoc` (`MaMonHoc` ASC) VISIBLE,
  INDEX `idx_lophoc_giaovien` (`MaGiaoVien` ASC) VISIBLE,
  CONSTRAINT `lophoc_ibfk_1`
    FOREIGN KEY (`MaKhoaHoc`)
    REFERENCES `lab4`.`khoahoc` (`MaKhoaHoc`)
    ON DELETE CASCADE,
  CONSTRAINT `lophoc_ibfk_2`
    FOREIGN KEY (`MaMonHoc`)
    REFERENCES `lab4`.`monhoc` (`MaMonHoc`)
    ON DELETE CASCADE,
  CONSTRAINT `lophoc_ibfk_3`
    FOREIGN KEY (`MaGiaoVien`)
    REFERENCES `lab4`.`giaovien` (`MaGiaoVien`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`dangky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`dangky` ;

CREATE TABLE IF NOT EXISTS `lab4`.`dangky` (
  `MaDangKy` VARCHAR(10) NOT NULL,
  `MaHocVien` VARCHAR(10) NOT NULL,
  `MaLop` VARCHAR(10) NOT NULL,
  `NgayDangKy` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `BienLai` VARCHAR(50) NULL DEFAULT NULL,
  `SoTienDong` DECIMAL(10,2) NULL DEFAULT NULL,
  `TrangThaiDong` SMALLINT NULL DEFAULT '1' COMMENT '1: Chưa đóng, 2: Đã đóng, 3: Đóng một phần',
  `GhiChu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`MaDangKy`),
  UNIQUE INDEX `uk_dangky_hocvien_lop` (`MaHocVien` ASC, `MaLop` ASC) VISIBLE,
  INDEX `idx_dangky_hocvien` (`MaHocVien` ASC) VISIBLE,
  INDEX `idx_dangky_lop` (`MaLop` ASC) VISIBLE,
  CONSTRAINT `dangky_ibfk_1`
    FOREIGN KEY (`MaHocVien`)
    REFERENCES `lab4`.`hocvien` (`MaHocVien`)
    ON DELETE CASCADE,
  CONSTRAINT `dangky_ibfk_2`
    FOREIGN KEY (`MaLop`)
    REFERENCES `lab4`.`lophoc` (`MaLop`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`day`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`day` ;

CREATE TABLE IF NOT EXISTS `lab4`.`day` (
  `MaGiaoVien` VARCHAR(10) NOT NULL,
  `MaLop` VARCHAR(10) NOT NULL,
  `NgayBatDau` DATE NULL DEFAULT NULL,
  `NgayKetThuc` DATE NULL DEFAULT NULL,
  `SoTietDay` INT NULL DEFAULT '0',
  `GhiChu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`MaGiaoVien`, `MaLop`),
  INDEX `MaLop` (`MaLop` ASC) VISIBLE,
  CONSTRAINT `day_ibfk_1`
    FOREIGN KEY (`MaGiaoVien`)
    REFERENCES `lab4`.`giaovien` (`MaGiaoVien`)
    ON DELETE CASCADE,
  CONSTRAINT `day_ibfk_2`
    FOREIGN KEY (`MaLop`)
    REFERENCES `lab4`.`lophoc` (`MaLop`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lab4`.`diem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab4`.`diem` ;

CREATE TABLE IF NOT EXISTS `lab4`.`diem` (
  `MaDiem` VARCHAR(10) NOT NULL,
  `MaHocVien` VARCHAR(10) NOT NULL,
  `MaMonHoc` VARCHAR(10) NOT NULL,
  `DiemLyThuyet` DECIMAL(3,1) NULL DEFAULT NULL,
  `DiemThucHanh` DECIMAL(3,1) NULL DEFAULT NULL,
  `NgayThi` DATE NULL DEFAULT NULL,
  `LanThi` INT NULL DEFAULT '1',
  `DiemTrungBinh` DECIMAL(3,1) GENERATED ALWAYS AS (((`DiemLyThuyet` + `DiemThucHanh`) / 2)) STORED,
  `KetQua` SMALLINT GENERATED ALWAYS AS ((case when ((`DiemLyThuyet` >= 5) and (`DiemThucHanh` >= 5)) then 1 else 2 end)) STORED COMMENT '1: Đạt, 2: Không đạt',
  `GhiChu` TEXT NULL DEFAULT NULL,
  `NgayNhap` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MaDiem`),
  UNIQUE INDEX `uk_diem_hocvien_monhoc_lanthi` (`MaHocVien` ASC, `MaMonHoc` ASC, `LanThi` ASC) VISIBLE,
  INDEX `idx_diem_hocvien` (`MaHocVien` ASC) VISIBLE,
  INDEX `idx_diem_monhoc` (`MaMonHoc` ASC) VISIBLE,
  INDEX `idx_diem_ngaythi` (`NgayThi` ASC) VISIBLE,
  CONSTRAINT `diem_ibfk_1`
    FOREIGN KEY (`MaHocVien` , `MaMonHoc`)
    REFERENCES `lab4`.`hoc` (`MaHocVien` , `MaMonHoc`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
